language: python
python:
- '3.5'
install:
- pip install -r requirements.txt
- pip install .
script: py.test
deploy:
  provider: pypi
  user: datacamp
  password:
    secure: "hJ5cdK5vNsxq1w9SqlAVesWzqQfI0hJZvyjvM+6anY6VIiezVsHIRKMNolNRrNG8skNY0eoIoeUbrEEtO7rz3vtErk0J1NL9VlVAWKYLy90+eRGxUAHk63CMWbYKcx5W+2EhYaCskBozjaLbTyYPEHAtReAS0ICgdHPIvt1DmV0r+3IEmN9BYe4r2KoIKxsUcSaGF5ND2t/yTRrzXtDeAy7BjYG5S2jw9SPpRkRzWU9+auS6rD9aQO0OSUsOnjBL5ELj5O8kImd9QqJjegeEPfjDK2Oc8gnHELlSB2cnS7+PpqolN8Z3utvAfHeN6E/ApCUj0iRQh5ruE5mD3cO6pd8cXFkpTWXVn8pL5GYwpuYXX7/9Dt3snowOJVAlhhce7pVw16STbXPeeBsabzyf1jYcEoJwdRX9is5WweqXvtS2LDEu3ZMi1QjQ0mIrQkb17TJwnIjx5fbOLInnkAc2/stl44oByzrG5/QnvqhQ52j9Nywzg0kx+OETaXztOJRqyM5yXvH28uOf8dMmMBaQeKxykozbnDJrWiC56uT2pd3hv1JCNyToTdYYCaHR1NfnozwZEvEyqwP5ZuAh7tO1cRIU5loL+72rjq5CkZGXqKFGcnvJpK4xCoY6V3dj/J839N08QDXs0etGFMnQsFBEpApIEhX7BN45Zu2bPOn2Vj4="
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: datacamp/antlr-ast
  skip_upload_docs: true
