language: python
python:
- '3.5'
install:
- pip install -r requirements.txt
- pip install .
script: py.test
deploy:
  provider: pypi
  user: datacamp
  password:
    secure: TfvWawxxcZkcE6VqhQ9Wj4m0XVYv6o+RLA77aO5JYSepzAt/52wFtUJjuDGUsiY7huUNFpAlEpYqxFhH8T68HUGcDKEKCyj8BwbE+Xvx7ZiYbRGReUmKJmW2qWFqczlEY2KdjiG5yUomQDv3NolJdI/ezhJvTi2AOOMLw0FJgwiBdNS2HtvuWTPmV+RTd76aIY4YIOwMvhoXQ5VVQuK1sMVjjxEXog4kYn8/cyEisfYnK5+tMX5wjMADuPSZyXl4Ze9RpLEM6A+xuO012T/sFq0YcTsCtSn9D0eWLAilsefIWr0OeriOHTblQ6pW3bMBcnQN2jFWCyFiPzp/OptuFYGu47jDIDCarQ0kq0g0IBCYIfuayYcaRkfBkdbcLTGbUqdsi1V6Xtc5EB8n3o14IuDKYudLQis84OLhYObJCYgqAHEZrEx6q0BC1T1VhvZHZkMh7/uCagRUffwPkuLSEL+oUqdAa6E/wDenJI1O8DNtpmlemuJcrAI717He5nDEuggWtxfBlr2Er9fZjAZVBqO793jMGfho4/i5VhVGPxsf3WEATBdCDcBGl1s25RGp4XQVaIVdETZ6WkC79i3OkEqw+iH6/CGkC5JB0DaEidsv9t9qvF2zWQC/fLHULYZKRM3BR5vO1ArR3viw1zrXjR44neDsQECqmTtpHShq6kA=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: datacamp/antlr-ast
  skip_upload_docs: true
