language: python
python:
- '3.5'
install:
- pip install -r requirements.txt
- pip install .
script: py.test
deploy:
  provider: pypi
  user: datacamp
  password:
    secure: dRucOUmlqO0iynrwN+7DhNFjCm6O7HVFjdNLRfo1+7lCQukuQTb8lwOWNuvoAaJzVaP9Dsid4bx/8SZkHqHmc/CcuslbKDPW6z7rYmxV2NAQqsnrgYX7IDxuEKc0alO6eXnKWyadPYcYBeLrz/HhVA7o7BJxr6CNEAUR03zl7ms1Gr0I82HtaGQYqWS7/jEj4/8AZL3uonevw1W4WrWr1HB1sM5g8wr60wlZmrwtbgd3peZvnfWsWGzeRQxX8xNFxRtDvRGNqlv8SMEEiyRGa0K/O/gXEyyNoiUfP35G8dGGj38LafzqU98hxBS5DiM59cHDuW1NurXQPrHi1Lb8unFMY6lfWt9+KMwctdMIBfyZR6lcXhgX33dR5VsHcHpALkKAq+BCd1gnYz7XT5Zmlq5KD+E793hiofXPfLhr/4CLuC0acPZIhFG6XLtZWNgwgkVCC3BAvWOJYl4tV/OuQjCWwLZLP+NA/8JvBNiI/2hGivT77/AYBtZTUfyG7+4rcEWudkfcpQExz55/cQWAACf3wcpET+dyNQYAU4mJ+l7eiB2Uf0mQq8Xdf5agXhMieykx+kstMcBN7qDXMTLagXmqnb45OOgJFrbJvIha0qfblUC2ktiUHGBZskA2/ovSzYqY+IGnURmRoCB5T10q7lJz37uJ00RTjaDkwLl9ROc=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: datacamp/antlr-ast
  skip_upload_docs: true
